const Test = () => {
  throw new Error("일부러 발생 시킨 오류");
};

export default Test;
